### ISSUE TITLE
Adding Resources

### ISSUE THREAD

**Issue by gsmithline** [SimonHashtag/EconRL#4]
Here are some good MARL Publications:
- [AI-driven Prices for Externalities and Sustainability in Production Markets](https://arxiv.org/abs/2106.06060)
- [The AI Economist: Improving Equality and Productivity with AI-Driven Tax Policies](https://www.science.org/doi/10.1126/sciadv.abk2607)

**Comment by SimonHashtag** [comment]
Both are already in the list. I updated the citation of Zheng et al (the list contained the working paper version). Thank you.
